" Name:         IntelliJ Light Theme
" Description:  A colorschema inspired by the beautiful IntelliJ Light theme.
" Author:       Gilbert Francois Duivesteijn
" Maintainer:   Gilbert Francois Duivesteijn
" Website:      https://www.blitzblit.com
" License:      Apache License 2.0
" Last Updated: Thu 06 May 2021 08:51:52 PM UTC

" Generated by Colortemplate v2.1.0

set background=light

hi clear
let g:colors_name = 'intellij_light'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running') || has('nvim')

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#000000', '#ff0000', '#00ff00', '#ffff00', '#0000ff', '#ff00ff', '#00ffff', '#808080', '#d2d2d2', '#ff6400', '#64ff00', '#ffff64', '#0064ff', '#ff64ff', '#64ffff', '#ffffff']
  if has('nvim')
    let g:terminal_color_0 = '#000000'
    let g:terminal_color_1 = '#ff0000'
    let g:terminal_color_2 = '#00ff00'
    let g:terminal_color_3 = '#ffff00'
    let g:terminal_color_4 = '#0000ff'
    let g:terminal_color_5 = '#ff00ff'
    let g:terminal_color_6 = '#00ffff'
    let g:terminal_color_7 = '#808080'
    let g:terminal_color_8 = '#d2d2d2'
    let g:terminal_color_9 = '#ff6400'
    let g:terminal_color_10 = '#64ff00'
    let g:terminal_color_11 = '#ffff64'
    let g:terminal_color_12 = '#0064ff'
    let g:terminal_color_13 = '#ff64ff'
    let g:terminal_color_14 = '#64ffff'
    let g:terminal_color_15 = '#ffffff'
  endif
  if get(g:, 'light_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#000000 guibg=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#000000 guibg=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
    hi Terminal guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=NONE guibg=#fffae3 gui=NONE cterm=NONE
  hi Conceal guifg=#800000 guibg=NONE gui=NONE cterm=NONE
  hi Cursor guifg=NONE guibg=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorIM guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#fffae3 gui=NONE cterm=NONE
  hi Directory guifg=#000080 guibg=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=#bee6be guibg=#000000 gui=reverse cterm=reverse
  hi DiffChange guifg=#cad9fa guibg=#000000 gui=reverse cterm=reverse
  hi DiffDelete guifg=#c8c8c8 guibg=#000000 gui=reverse cterm=reverse
  hi DiffText guifg=#ffff00 guibg=#808000 gui=reverse cterm=reverse
  hi! link EndOfBuffer Normal
  hi ErrorMsg guifg=#ffffff guibg=#ff0000 gui=reverse cterm=reverse
  hi VertSplit guifg=#dddddd guibg=NONE gui=NONE cterm=NONE
  hi Folded guifg=#808080 guibg=#c0c0c0 gui=NONE cterm=NONE
  hi FoldColumn guifg=#808080 guibg=#c0c0c0 gui=NONE cterm=NONE
  hi SignColumn guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi IncSearch guifg=fg guibg=#ffff00 gui=NONE cterm=NONE
  hi Substitute guifg=#ff00ff guibg=#004000 gui=NONE cterm=NONE
  hi LineNr guifg=#dddddd guibg=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#000000 guibg=#fffae3 gui=NONE cterm=NONE
  hi MatchParen guifg=fg guibg=#808000 gui=NONE cterm=NONE
  hi ModeMsg guifg=#000000 guibg=NONE gui=bold cterm=bold
  hi! link MsgArea Normal
  hi! link MsgSeparator Normal
  hi MoreMsg guifg=#660099 guibg=NONE gui=NONE cterm=NONE
  hi NonText guifg=#800000 guibg=NONE gui=NONE cterm=NONE
  hi NormalFloat guifg=#000000 guibg=#dddddd gui=NONE cterm=NONE
  hi! link NormalNC Normal
  hi Pmenu guifg=#000000 guibg=#f2f2f2 gui=NONE cterm=NONE
  hi PmenuSel guifg=#ffffff guibg=#4577e3 gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#ececec gui=NONE cterm=NONE
  hi PmenuThumb guifg=NONE guibg=#dddddd gui=NONE cterm=NONE
  hi Question guifg=#ff00ff guibg=#004000 gui=NONE cterm=NONE
  hi QuickFixLine guifg=#ff00ff guibg=#004000 gui=NONE cterm=NONE
  hi Search guifg=#ffff00 guibg=#000000 gui=reverse cterm=reverse
  hi SpecialKey guifg=#ff00ff guibg=#004000 gui=NONE cterm=NONE
  hi SpellBad guifg=#ff00ff guibg=NONE guisp=#d2d2d2 gui=undercurl cterm=underline
  hi SpellCap guifg=#ff00ff guibg=NONE guisp=#d2d2d2 gui=undercurl cterm=underline
  hi SpellLocal guifg=#ff00ff guibg=NONE guisp=#d2d2d2 gui=undercurl cterm=underline
  hi SpellRare guifg=#ff00ff guibg=NONE guisp=#d2d2d2 gui=undercurl cterm=underline
  hi StatusLine guifg=#000000 guibg=#dddddd gui=bold cterm=bold
  hi StatusLineNC guifg=#000000 guibg=#dddddd gui=NONE cterm=NONE
  hi TabLine guifg=#000000 guibg=#dddddd gui=NONE cterm=NONE
  hi TabLineFill guifg=#000000 guibg=#ececec gui=NONE cterm=NONE
  hi TabLineSel guifg=#ffffff guibg=#4577e3 gui=NONE cterm=NONE
  hi Title guifg=#000000 guibg=NONE gui=NONE cterm=NONE
  hi Visual guifg=#5974ab guibg=#ffffff gui=reverse cterm=reverse
  hi VisualNOS guifg=#ffffff guibg=#5974ab gui=NONE cterm=NONE
  hi WarningMsg guifg=#000000 guibg=#808000 gui=reverse cterm=reverse
  hi Whitespace guifg=#000000 guibg=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#ffffff guibg=#ff00ff gui=NONE cterm=NONE
  hi Comment guifg=#c0c0c0 guibg=NONE gui=italic cterm=italic
  hi Constant guifg=#660099 guibg=NONE gui=bold,italic cterm=bold,italic
  hi String guifg=#008000 guibg=NONE gui=NONE cterm=NONE
  hi Character guifg=#000080 guibg=NONE gui=bold cterm=bold
  hi Number guifg=#0000ff guibg=NONE gui=NONE cterm=NONE
  hi Boolean guifg=#000080 guibg=NONE gui=bold cterm=bold
  hi Float guifg=#000080 guibg=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#000000 guibg=NONE gui=NONE cterm=NONE
  hi Function guifg=#000000 guibg=NONE gui=NONE cterm=NONE
  hi Statement guifg=#000080 guibg=NONE gui=bold cterm=bold
  hi Conditional guifg=#000080 guibg=NONE gui=bold cterm=bold
  hi Repeat guifg=#000080 guibg=NONE gui=bold cterm=bold
  hi Label guifg=#000080 guibg=NONE gui=bold cterm=bold
  hi Operator guifg=#000000 guibg=NONE gui=NONE cterm=NONE
  hi Keyword guifg=#000080 guibg=NONE gui=bold cterm=bold
  hi Exception guifg=#000080 guibg=NONE gui=bold cterm=bold
  hi PreProc guifg=#808080 guibg=NONE gui=NONE cterm=NONE
  hi Include guifg=#000080 guibg=NONE gui=bold cterm=bold
  hi Define guifg=#808080 guibg=NONE gui=NONE cterm=NONE
  hi Macro guifg=#808080 guibg=NONE gui=NONE cterm=NONE
  hi PreCondit guifg=#808080 guibg=NONE gui=NONE cterm=NONE
  hi Type guifg=#000000 guibg=NONE gui=NONE cterm=NONE
  hi StorageClass guifg=#000000 guibg=NONE gui=NONE cterm=NONE
  hi Structure guifg=#000000 guibg=NONE gui=NONE cterm=NONE
  hi Typedef guifg=#000000 guibg=NONE gui=NONE cterm=NONE
  hi Special guifg=#000000 guibg=NONE gui=NONE cterm=NONE
  hi SpecialChar guifg=#000000 guibg=NONE gui=NONE cterm=NONE
  hi Tag guifg=#000000 guibg=NONE gui=NONE cterm=NONE
  hi Delimiter guifg=#000000 guibg=NONE gui=NONE cterm=NONE
  hi SpecialComment guifg=#000000 guibg=NONE gui=NONE cterm=NONE
  hi Debug guifg=#000000 guibg=NONE gui=NONE cterm=NONE
  hi Underlined guifg=NONE guibg=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi Error guifg=#ff0000 guibg=NONE gui=underline cterm=underline
  hi Todo guifg=#000000 guibg=#ffff00 gui=NONE cterm=NONE
  hi pythonString guifg=#008080 guibg=NONE gui=bold cterm=bold
  hi pythonClassVar guifg=#94558d guibg=NONE gui=NONE cterm=NONE
  hi pythonDecorator guifg=#660099 guibg=NONE gui=NONE cterm=NONE
  hi pythonInclude guifg=#000080 guibg=NONE gui=bold cterm=bold
  hi pythonOperator guifg=#000080 guibg=NONE gui=bold cterm=bold
  hi pythonException guifg=#000080 guibg=NONE gui=NONE cterm=NONE
  hi pythonBoolean guifg=#000080 guibg=NONE gui=bold cterm=bold
  hi pythonAttribute guifg=#660099 guibg=NONE gui=NONE cterm=NONE
  hi! link pythonComment Comment
  hi CocErrorSign guifg=#800000 guibg=#ffd5cc gui=NONE cterm=NONE
  hi CocWarningSign guifg=#804000 guibg=#ffce9d gui=NONE cterm=NONE
  hi CocInfoSign guifg=#808000 guibg=#bee6be gui=NONE cterm=NONE
  hi CocHintSign guifg=#000080 guibg=#cad9fa gui=NONE cterm=NONE
  if !s:italics
    hi Comment gui=NONE cterm=NONE
    hi Constant gui=bold cterm=bold
  endif
  if has('nvim')
    hi! link TermCursor Cursor
    hi! link TermCursorNC CursorIM
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if get(g:, 'light_transp_bg', 0)
    hi Normal ctermfg=16 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=16 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=16 ctermbg=231 cterm=NONE
    hi Terminal ctermfg=16 ctermbg=231 cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=230 cterm=NONE
  hi Conceal ctermfg=88 ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorIM ctermfg=16 ctermbg=231 cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=230 cterm=NONE
  hi Directory ctermfg=18 ctermbg=NONE cterm=NONE
  hi DiffAdd ctermfg=151 ctermbg=16 cterm=reverse
  hi DiffChange ctermfg=189 ctermbg=16 cterm=reverse
  hi DiffDelete ctermfg=251 ctermbg=16 cterm=reverse
  hi DiffText ctermfg=226 ctermbg=100 cterm=reverse
  hi! link EndOfBuffer Normal
  hi ErrorMsg ctermfg=231 ctermbg=196 cterm=reverse
  hi VertSplit ctermfg=253 ctermbg=NONE cterm=NONE
  hi Folded ctermfg=244 ctermbg=250 cterm=NONE
  hi FoldColumn ctermfg=244 ctermbg=250 cterm=NONE
  hi SignColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi IncSearch ctermfg=fg ctermbg=226 cterm=NONE
  hi Substitute ctermfg=201 ctermbg=22 cterm=NONE
  hi LineNr ctermfg=253 ctermbg=NONE cterm=NONE
  hi CursorLineNr ctermfg=16 ctermbg=230 cterm=NONE
  hi MatchParen ctermfg=fg ctermbg=100 cterm=NONE
  hi ModeMsg ctermfg=16 ctermbg=NONE cterm=bold
  hi! link MsgArea Normal
  hi! link MsgSeparator Normal
  hi MoreMsg ctermfg=54 ctermbg=NONE cterm=NONE
  hi NonText ctermfg=88 ctermbg=NONE cterm=NONE
  hi NormalFloat ctermfg=16 ctermbg=253 cterm=NONE
  hi! link NormalNC Normal
  hi Pmenu ctermfg=16 ctermbg=255 cterm=NONE
  hi PmenuSel ctermfg=231 ctermbg=33 cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=254 cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=253 cterm=NONE
  hi Question ctermfg=201 ctermbg=22 cterm=NONE
  hi QuickFixLine ctermfg=201 ctermbg=22 cterm=NONE
  hi Search ctermfg=226 ctermbg=16 cterm=reverse
  hi SpecialKey ctermfg=201 ctermbg=22 cterm=NONE
  hi SpellBad ctermfg=201 ctermbg=NONE cterm=underline
  hi SpellCap ctermfg=201 ctermbg=NONE cterm=underline
  hi SpellLocal ctermfg=201 ctermbg=NONE cterm=underline
  hi SpellRare ctermfg=201 ctermbg=NONE cterm=underline
  hi StatusLine ctermfg=16 ctermbg=253 cterm=bold
  hi StatusLineNC ctermfg=16 ctermbg=253 cterm=NONE
  hi TabLine ctermfg=16 ctermbg=253 cterm=NONE
  hi TabLineFill ctermfg=16 ctermbg=254 cterm=NONE
  hi TabLineSel ctermfg=231 ctermbg=33 cterm=NONE
  hi Title ctermfg=16 ctermbg=NONE cterm=NONE
  hi Visual ctermfg=68 ctermbg=231 cterm=reverse
  hi VisualNOS ctermfg=231 ctermbg=68 cterm=NONE
  hi WarningMsg ctermfg=16 ctermbg=100 cterm=reverse
  hi Whitespace ctermfg=16 ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=231 ctermbg=201 cterm=NONE
  hi Comment ctermfg=250 ctermbg=NONE cterm=italic
  hi Constant ctermfg=54 ctermbg=NONE cterm=bold,italic
  hi String ctermfg=28 ctermbg=NONE cterm=NONE
  hi Character ctermfg=18 ctermbg=NONE cterm=bold
  hi Number ctermfg=21 ctermbg=NONE cterm=NONE
  hi Boolean ctermfg=18 ctermbg=NONE cterm=bold
  hi Float ctermfg=18 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=16 ctermbg=NONE cterm=NONE
  hi Function ctermfg=16 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=18 ctermbg=NONE cterm=bold
  hi Conditional ctermfg=18 ctermbg=NONE cterm=bold
  hi Repeat ctermfg=18 ctermbg=NONE cterm=bold
  hi Label ctermfg=18 ctermbg=NONE cterm=bold
  hi Operator ctermfg=16 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=18 ctermbg=NONE cterm=bold
  hi Exception ctermfg=18 ctermbg=NONE cterm=bold
  hi PreProc ctermfg=244 ctermbg=NONE cterm=NONE
  hi Include ctermfg=18 ctermbg=NONE cterm=bold
  hi Define ctermfg=244 ctermbg=NONE cterm=NONE
  hi Macro ctermfg=244 ctermbg=NONE cterm=NONE
  hi PreCondit ctermfg=244 ctermbg=NONE cterm=NONE
  hi Type ctermfg=16 ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=16 ctermbg=NONE cterm=NONE
  hi Structure ctermfg=16 ctermbg=NONE cterm=NONE
  hi Typedef ctermfg=16 ctermbg=NONE cterm=NONE
  hi Special ctermfg=16 ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=16 ctermbg=NONE cterm=NONE
  hi Tag ctermfg=16 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=16 ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=16 ctermbg=NONE cterm=NONE
  hi Debug ctermfg=16 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi Error ctermfg=88 ctermbg=NONE cterm=underline
  hi Todo ctermfg=16 ctermbg=226 cterm=NONE
  hi pythonString ctermfg=30 ctermbg=NONE cterm=bold
  hi pythonClassVar ctermfg=96 ctermbg=NONE cterm=NONE
  hi pythonDecorator ctermfg=54 ctermbg=NONE cterm=NONE
  hi pythonInclude ctermfg=18 ctermbg=NONE cterm=bold
  hi pythonOperator ctermfg=18 ctermbg=NONE cterm=bold
  hi pythonException ctermfg=18 ctermbg=NONE cterm=NONE
  hi pythonBoolean ctermfg=18 ctermbg=NONE cterm=bold
  hi pythonAttribute ctermfg=54 ctermbg=NONE cterm=NONE
  hi! link pythonComment Comment
  hi CocErrorSign ctermfg=88 ctermbg=224 cterm=NONE
  hi CocWarningSign ctermfg=130 ctermbg=223 cterm=NONE
  hi CocInfoSign ctermfg=100 ctermbg=151 cterm=NONE
  hi CocHintSign ctermfg=18 ctermbg=189 cterm=NONE
  if !s:italics
    hi Comment cterm=NONE
    hi Constant cterm=bold
  endif
  if has('nvim')
    hi! link TermCursor Cursor
    hi! link TermCursorNC CursorIM
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'light_transp_bg', 0)
    hi Normal ctermfg=Black ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=Black ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi Terminal ctermfg=Black ctermbg=LightGrey cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=LightYellow cterm=NONE
  hi Conceal ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorIM ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=LightYellow cterm=NONE
  hi Directory ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi DiffAdd ctermfg=DarkGreen ctermbg=Black cterm=reverse
  hi DiffChange ctermfg=DarkBlue ctermbg=Black cterm=reverse
  hi DiffDelete ctermfg=DarkGrey ctermbg=Black cterm=reverse
  hi DiffText ctermfg=Yellow ctermbg=DarkYellow cterm=reverse
  hi! link EndOfBuffer Normal
  hi ErrorMsg ctermfg=LightGrey ctermbg=DarkRed cterm=reverse
  hi VertSplit ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi Folded ctermfg=DarkGrey ctermbg=LightGrey cterm=NONE
  hi FoldColumn ctermfg=DarkGrey ctermbg=LightGrey cterm=NONE
  hi SignColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi IncSearch ctermfg=fg ctermbg=Yellow cterm=NONE
  hi Substitute ctermfg=DarkMagenta ctermbg=DarkGreen cterm=NONE
  hi LineNr ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi CursorLineNr ctermfg=Black ctermbg=LightYellow cterm=NONE
  hi MatchParen ctermfg=fg ctermbg=DarkYellow cterm=NONE
  hi ModeMsg ctermfg=Black ctermbg=NONE cterm=bold
  hi! link MsgArea Normal
  hi! link MsgSeparator Normal
  hi MoreMsg ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi NonText ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi NormalFloat ctermfg=Black ctermbg=DarkGrey cterm=NONE
  hi! link NormalNC Normal
  hi Pmenu ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi PmenuSel ctermfg=LightGrey ctermbg=LightBlue cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi Question ctermfg=DarkMagenta ctermbg=DarkGreen cterm=NONE
  hi QuickFixLine ctermfg=DarkMagenta ctermbg=DarkGreen cterm=NONE
  hi Search ctermfg=Yellow ctermbg=Black cterm=reverse
  hi SpecialKey ctermfg=DarkMagenta ctermbg=DarkGreen cterm=NONE
  hi SpellBad ctermfg=DarkMagenta ctermbg=NONE cterm=underline
  hi SpellCap ctermfg=DarkMagenta ctermbg=NONE cterm=underline
  hi SpellLocal ctermfg=DarkMagenta ctermbg=NONE cterm=underline
  hi SpellRare ctermfg=DarkMagenta ctermbg=NONE cterm=underline
  hi StatusLine ctermfg=Black ctermbg=DarkGrey cterm=bold
  hi StatusLineNC ctermfg=Black ctermbg=DarkGrey cterm=NONE
  hi TabLine ctermfg=Black ctermbg=DarkGrey cterm=NONE
  hi TabLineFill ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi TabLineSel ctermfg=LightGrey ctermbg=LightBlue cterm=NONE
  hi Title ctermfg=Black ctermbg=NONE cterm=NONE
  hi Visual ctermfg=LightBlue ctermbg=LightGrey cterm=reverse
  hi VisualNOS ctermfg=LightGrey ctermbg=LightBlue cterm=NONE
  hi WarningMsg ctermfg=Black ctermbg=DarkYellow cterm=reverse
  hi Whitespace ctermfg=Black ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=LightGrey ctermbg=DarkMagenta cterm=NONE
  hi Comment ctermfg=LightGrey ctermbg=NONE cterm=italic
  hi Constant ctermfg=DarkMagenta ctermbg=NONE cterm=bold,italic
  hi String ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Character ctermfg=DarkBlue ctermbg=NONE cterm=bold
  hi Number ctermfg=LightBlue ctermbg=NONE cterm=NONE
  hi Boolean ctermfg=DarkBlue ctermbg=NONE cterm=bold
  hi Float ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=Black ctermbg=NONE cterm=NONE
  hi Function ctermfg=Black ctermbg=NONE cterm=NONE
  hi Statement ctermfg=DarkBlue ctermbg=NONE cterm=bold
  hi Conditional ctermfg=DarkBlue ctermbg=NONE cterm=bold
  hi Repeat ctermfg=DarkBlue ctermbg=NONE cterm=bold
  hi Label ctermfg=DarkBlue ctermbg=NONE cterm=bold
  hi Operator ctermfg=Black ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=DarkBlue ctermbg=NONE cterm=bold
  hi Exception ctermfg=DarkBlue ctermbg=NONE cterm=bold
  hi PreProc ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi Include ctermfg=DarkBlue ctermbg=NONE cterm=bold
  hi Define ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi Macro ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi PreCondit ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi Type ctermfg=Black ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=Black ctermbg=NONE cterm=NONE
  hi Structure ctermfg=Black ctermbg=NONE cterm=NONE
  hi Typedef ctermfg=Black ctermbg=NONE cterm=NONE
  hi Special ctermfg=Black ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=Black ctermbg=NONE cterm=NONE
  hi Tag ctermfg=Black ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=Black ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=Black ctermbg=NONE cterm=NONE
  hi Debug ctermfg=Black ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi Error ctermfg=DarkRed ctermbg=NONE cterm=underline
  hi Todo ctermfg=Black ctermbg=Yellow cterm=NONE
  hi pythonString ctermfg=DarkCyan ctermbg=NONE cterm=bold
  hi pythonClassVar ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi pythonDecorator ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi pythonInclude ctermfg=DarkBlue ctermbg=NONE cterm=bold
  hi pythonOperator ctermfg=DarkBlue ctermbg=NONE cterm=bold
  hi pythonException ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi pythonBoolean ctermfg=DarkBlue ctermbg=NONE cterm=bold
  hi pythonAttribute ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi! link pythonComment Comment
  hi CocErrorSign ctermfg=DarkRed ctermbg=DarkRed cterm=NONE
  hi CocWarningSign ctermfg=LightRed ctermbg=LightYellow cterm=NONE
  hi CocInfoSign ctermfg=DarkYellow ctermbg=DarkGreen cterm=NONE
  hi CocHintSign ctermfg=DarkBlue ctermbg=DarkBlue cterm=NONE
  if !s:italics
    hi Comment cterm=NONE
    hi Constant cterm=bold
  endif
  if has('nvim')
    hi! link TermCursor Cursor
    hi! link TermCursorNC CursorIM
  endif
  unlet s:t_Co s:italics
  finish
endif

" Color: black         rgb(  0,   0,   0)        ~         Black
" Color: red           rgb(255,   0,   0)        ~         DarkRed
" Color: green         rgb(  0, 255,   0)        ~         DarkGreen
" Color: yellow        rgb(255, 255,   0)        ~         DarkYellow
" Color: blue          rgb(  0,   0, 255)        ~         DarkBlue
" Color: magenta       rgb(255,   0, 255)        ~         DarkMagenta
" Color: cyan          rgb(  0, 255, 255)        ~         DarkCyan
" Color: white         rgb(255, 255, 255)        ~         LightGrey
" Color: brightblack   rgb(210, 210, 210)        ~         DarkGrey
" Color: brightred     rgb(255, 100,   0)        ~         LightRed
" Color: brightgreen   rgb(100, 255,   0)        ~         LightGreen
" Color: brightyellow  rgb(255, 255, 100)        ~         LightYellow
" Color: brightblue    rgb(  0, 100, 255)        ~         LightBlue
" Color: brightmagenta rgb(255, 100, 255)        ~         LightMagenta
" Color: brightcyan    rgb(100, 255, 255)        ~         LightCyan
" Color: black1        #000000                   ~         Black
" Color: red1          #800000                  88         DarkRed  
" Color: red2          #FF0000                  88         DarkRed  
" Color: orange1       #804000                   ~         LightRed
" Color: orange2       #FF7F00                   ~         LightRed
" Color: green1        #008000                  28         DarkGreen         ; css string
" Color: green2        #00FF00                   ~         DarkGreen
" Color: yellow1       #808000                   ~         DarkYellow
" Color: yellow2       #FFFF00                   ~         Yellow
" Color: yellow3       #FFFAE3                 230         LightYellow       ; cursorline
" Color: blue1         #000080                  18         DarkBlue          ; python def
" Color: blue2         #0000FF                  21         LightBlue         ; python number
" Color: blue4         #0000B2                  19         DarkBlue          ; python decorator
" Color: purple1       #660099                  54         DarkMagenta       ; python param
" Color: purple2       #94558D                  96         DarkMagenta       ; python self
" Color: purple3       #660E7A                  54         DarkMagenta       ; python constant 
" Color: cyan1         #008080                  30         DarkCyan          ; python string
" Color: cyan2         #00FFFF                   ~         DarkCyan
" Color: silver        #c0c0c0                 250         LightGrey
" Color: gray          #808080                 244         DarkGrey
" Color: diffins       #BEE6BE                   ~         DarkGreen
" Color: diffdel       #C8C8C8                   ~         DarkGrey
" Color: diffcon       #FFD5CC                   ~         DarkRed
" Color: diffcha       #CAD9FA                   ~         DarkBlue
" Color: diffwar       #FFCE9D                   ~         LightYellow
" Color: guigray1      rgb(221, 221, 221)      253         DarkGrey
" Color: guigray2      rgb(236, 236, 236)      254         LightGrey
" Color: guigray3      rgb(242, 242, 242)      255         LightGrey
" Color: guipmenusel   rgb( 69, 119, 227)        ~         LightBlue
" Color: guivisual     rgb( 89, 116, 171)        ~         LightBlue
" Color: cocerror      rgb(220,   0,   0)        ~         DarkRed
" Color: cocwarn       rgb(220, 110,   0)        ~         LightRed
" Color: cocinfo       rgb(220, 220,   0)        ~         DarkYellow
" Color: cochint       rgb(  0, 110, 220)        ~         LightBlue
" Color: tmpfg         rgb(255,   0, 255)        ~         DarkMagenta
" Color: tmpbg         rgb(  0,  64,   0)        ~         DarkGreen
" Term colors: black       red       green       yellow       blue       magenta       cyan       gray 
" Term colors: brightblack brightred brightgreen brightyellow brightblue brightmagenta brightcyan white
" Background: light
" vim: et ts=2 sw=2
